## Import the types of troops
from troops import Cavalry, Archer, Infantry

##Import the blessings
from the_blessings import Hercules, Hermes, Artemis, blessingdrop, the_choice, archer_artemis, archer_hercules, archer_hermes, infantry_artemis, infantry_hercules, infantry_hermes, cavalry_artemis, cavalry_hercules, cavalry_hermes

##Import all the items
from the_armor import Shield, Boots, Cloak, Chestplate, item_drop, armorchoice, archer_boots, archer_chestplate, archer_cloak, archer_shield, infantry_chestplate, infantry_boots, infantry_shield, infantry_cloak, cavalry_boots, cavalry_chestplate, cavalry_cloak, cavalry_shield

##function
def logic():
    blessingdrop()
    the_choice()
    item_drop()
    armorchoice()

##Import the enemies
from enemies import Slime, Zombie, Goblin, Skeleton, Minotaur, Cyclops, GiantSpider, Yeti, Hydra, nelahWrM

##Import all of the arenas
from arena import beforearena, slimebattle, nextarena, nextarenafight, minoboss, colcavern, colcavernfight, GSboss, mountaintopofgi, mountaintopofgifi, hydraboss, Nelahwrmfight


print ("---------")
print ("Kato Productions Presents")
print ("BOTS Against the WORLD")
input ("---------")


def storyline():
    print ("The world has been run over by the overlord NelahWrM and his monstrous forces")
    print ("Many have suffered under his evil rule")
    input ("---")
    print ("The poor continue to be oppressed as they live their destitute lives")
    print ("Yet the wealthy live in luxury ")
    input ("---")
    print ("Many have attempted to revolt against NelahWrM")
    print ("Yet no one could match the devilish power of NelahWrM")
    input ("---")
    print ("The pioneers of resistance have left a lasting mark of hope")
    print ("It is now your task to bring his tryanny to its knees, as those past tried to do so")
    input ("---")
    print ("As the shady, strange man, dressed in violet, explained this valiant quest he presented you three figures ")
    input ("---")
    print ("The first was a posse of lanky men. They possessed long bows half their size")
    print ("The second was a troup of gruff individuals. They wielded monstrous blades")
    print ("The last were a formation of majestic horses and skilled riders")
    input ("---")
    print ("The figures could come alive and take the form of archers, infantry and cavalry")
    print ("Each figure possessed their own skill set which was nicely divided into three main stats")
    print ("These stats were health, attack and speed")
    input ("---")
    print ("Yet these stats were random courtesy of the man who carved them")
storyline()



def intro():
    input ("---")
    print ('The distant man was kind enough to offer you these figure for his journey had long ended')
    input ("---")
    input ("He presented you the Archer:")
    input ("---")
    print ("The figure presented you a random attack (8 - 10), a random speed (6 - 10), and a random health (5 - 10)")
    print ("- Attack: ", Archer.attack)
    print ("- Speed: ", Archer.speed )
    print ("- Health: ", Archer.health)
    input ("---")
    input ("Next, he presented you the Infantry:")
    input ("---")
    print ("The figure presented you a random attack (5 - 10), a random speed (6 - 10), and a random health (8 - 10)")
    print ("- Attack: ", Infantry.attack)
    print ("- Speed: ", Infantry.speed )
    print ("- Health: ", Infantry.health)
    input ("---")
    input ("Lastly, he presented you the Cavalry:")
    input ("---")
    print ("The figure presented you a random attack (6 - 10), a random speed (8 - 10), and a random health (5 - 10)")
    print ("- Attack: ", Cavalry.attack)
    print ("- Speed: ", Cavalry.speed )
    print ("- Health: ", Cavalry.health)
intro()

def nextpart():
    input ("---")
    print ("You bid your farwells to the distant man, as you prepared yourself for the mountainous quest you've been assigned ")
    print ("The strange man had informed you that the first of NelahWrm's strongholds was the ominous Swampy Swamp")
    input ("---")
    print ("As you approached the dark swamp a feeling of immense dread overcame you")
    print ("The power of NelahWrm was oozing all over")
    input ("---")
    print ("As you entered the swamp the thick substance clinged to your legs dragging you down in the process")
    input ("---")
    print ("Each step was a struggle and the first of NelahWrm's servants emerged from the swamp, The SLIME.")
nextpart()

def firstbattle():
    print ("As you scrambled to find your footing you fumbled through your sack to find your figures")
    print ("You're fingers felt the soft wooden figures; you returned to a sense of indomitable focus")
    input ("---")   
    beforearena()
    input ("---")
    slimebattle()
    logic()
    input ("---")
firstbattle()

def secondbattle():
    print ("You managed to make it past the battle with minimal damage")
    print ("The SLIME was a simple yet troublesome enemy if anyone else had encountered it")
    input ("---")
    print ("Amazed at the newfound power of the figure, you continue to travel through the SWAMP")
    print ("Each step was one of caution")
    input ("---")
    print ("The air grew heavy as your nerves tensed for evil was around the corner")
    print ("The next of NELAHWRM's servants revealed themselves")
    input ("---")
    beforearena()
    input("---")
    nextarena()
    nextarenafight()
    logic()
    input("---")
    print ("Your previous enemy stood no chance")
    print ("Yet the SWAMP grew deeper and air began to reek of rot")
    print ("You could feel his essence grow more apparent")
    input ("---")
    print ("You began to sense evil")
    print ("The next of NELAHWRM's servants revealed themselves")
    input ("---")
    beforearena()
    input("---")
    nextarena()
    nextarenafight()
    logic()
    input("---")
    print ("Yet again another enemy stood in shambles")
    print ("The SWAMP clung to your legs")
    print ("It wouldn't let go")
    input ("---")
    print ("The presence of evil returned")
    print ("The next of NELAHWRM'S servants revealed themselves")
    input ("---")
    beforearena()
    input("---")
    nextarena()
    nextarenafight()
    logic()
    input("---")
    print ("The air grew lighter as if the SWAMP released its clutches")
    print ("The light grew bright")
    print ("You escaped the SWAMPY SWAMP")
secondbattle()

def mino():
    input ("---")
    print ("Shortly after, you found yourself in a massive field")
    print ("The air was fresh yet evil still lingered")
    input ("---")
    print ("A sudden flash screamed past")
    print ("You fell to the ground, startled at the very speed")
    print ("You found your footing and began to search the field")
    input ("---")
    print ("This FOE was of a higher class")
    input ("---")
    beforearena()
    input("---")
    minoboss()
    logic()
    input ("---")
    print ("Your figures began to wear")
    print ("The MIGHTY MINOTAUR proved itself a capable foe")
    print ("You earned a taste of NELAHWRM power")
mino()

def mountarena():
    input ("---")
    print ("You continued the arduous trek ")
    print ("The sheer size of the field posed a taxing challenge")
    input ("---")
    print ("During your travels you encountered many a village")
    print ("The inhabitants lived a simple life; many were farmers")
    print ('The occasional artisan could be found; yet their lives were still crude')
    input ("---")
    print ("However, you could still sense corruption within their straightforward existence")
    print ("There were few that carried themselves so great")
    print ("Few that possessed wealth such as that")
    print ("Servants of Nelahwrm ruled with an iron fist")
    input ("---")
    print ("At the end of the field stood a grand mountain")
    print ("Yet around its base lay the essence of Nelahwrm, it was tainted")
    input ("---")
    print ("The next of Nelahwrm's strongholds was here the MOUNTAINOUS MOUNTAIN")
    input ("---")
    print ("You began to search for a way to scale the mountain")
    print ("You stumbled upon a convient opening within the mountain")
    input ("---")
    print ("THE COLOSSAL CAVERN")
    input ("---")
    print ("As you made your way the darkness grew as if the light was snuffed out")
    print ("Nelahwrm presence grew to be overwhelming")
    print ("The next of his servants appeared")
    input ("---")
    beforearena()
    input()
    colcavern()
    colcavernfight()
    logic()
    input ("---")
    print ("Definetely a formidable foe, yet it's corruption still crumbled")
    print ("The scale of the enemies had truly grew")
    input ("---")
    print ("The darkness embraced you as Nelahwrm's influenced lurked in the shadows")
    print ("The cavern was humid and lacked the free breeze")
    print ("Evil was trapped within air as your next foe appeared")
    input ("---")
    beforearena()
    input()
    colcavern()
    colcavernfight()
    logic()
    print ("The air grew cold, as draft ran through")
    print ("The COLASSAL CAVERN was liberated")
mountarena()

def spider():
    input("---")
    print("The light began to pierce through the cave")
    print("The exit was near")
    input("---")
    print("You began to explore the mountain, searching for a way to the top")
    print("Yet suddenly you could feel a darkness pierce through you")
    print("Silk covered the ground as you spotted the eyes of GIANT SPIDER")
    input("---")
    print("You encountered it domain, many a victim to its web")
    print("It's victim stared back as they remained hollow husks")
    input("---")
    print ("This FOE was of a higher class")
    input ("---")
    beforearena()
    input("---")
    GSboss()
    logic()
    input ("---")
    print ("Your figured decreased in condition")
    print ("The GINORMOUS GIANT SPIDER proved itself a formidable foe")
    print ("NELAHWRM's power flowed")
spider()

def spinemon():
    input("---")
    print("A trail revealed itself past the webs of the GIANT SPIDER ")
    print("It eventually led to the spine of the mountain")
    input("---")
    print("The SISYPHEAN SPINE stood before you")
    input("---")
    print("You attempted to scale the spine yet each step was demanding")
    print("The sheer altitude made it challenging")
    print("The air was thinning as if someone was stealing it")
    input("---")
    print("Nelahwrm presence grew as your next enemy appeared")
    input("---")
    beforearena()
    input("---")
    mountaintopofgi()
    mountaintopofgifi()
    logic()
    input("---")
    print("The climb exanded in intensity as you began to gasp for breath")
    print("The air was cold and sucked the warmth from your body")
    input("---")
    print("The gales had grown still, as Nelahwrm intruded")
    input("---")
    beforearena()
    input("---")
    mountaintopofgi()
    mountaintopofgifi()
    logic()
    input("---")
    print("The spine had come to clearing")
    print("Frost laid barren on the rocky the surface")
    input("---")
    print("A distant roaring could be heard")
    print("A sudden bolt a flame lit up the sky")
    print("A silhouette of 6 wings was revealed")
spinemon()

def Hydrafi():
    input("---")
    print ("The HORRID HYDRA is the last FOE that stands in your way ")
    input("---")
    beforearena()
    input("---")
    hydraboss()
    logic()
    print ("Nelahwrm essence dissapated as the HYDRA lay vanquished")
    input ("---")
    print ("You figures were now nearing their limit")
    print ("The final task was to reach the SUMMIT")
    print ("A shining ray of purple gleamed from the top")
    input ("---")
    print ("Nelahwrm was sure to be there")

def NelahWrMfi():
    input ("---")
    print ("The SUMMIT boasted its wickedness")
    print ("Unnerving pressure built up around you")
    input ("---")
    print ("As you ascended to top, a familiar face greeted you")
    print ("For it was the old man dressed in violet")
    input ("---")
    print ("He began to reveal to you that he once conquered the world using the very figures you wielded")
    print ("Nelahwrm proclaimed that he remained lonely as no one could attest to his power")
    print ("That was when you arrived a being worthy to rival him")
    input ("---")
    print ("Nelahwrm began to cackle")
    print ("You grew uncomfortable as you clutched you figures")
    print ("This was it")
    input ("---")
    beforearena()
    input("---")
    Nelahwrmfight()
    input ("---")
    input ("As Nelahwrm drew his final breath...")
    input ("Your figures shattered ")
    input ("Finally releasing the world from all remnants of NELAHWRM")
NelahWrMfi()

def outro():
    input("-----")
    print ("Kato Productions: ")
    print ("BOTS Against the WORLD")
    input("-----")
    print ("Game produced by Kiro and Batu")
    input("-----")
    print ("Read Nelahwrm backwards, heh")
outro()
    

    